package ru.skilllbox.diplom.group40.social.service.dto.business.object;


public enum Type {
    LIKE, POST, POST_COMMENT, COMMENT_COMMENT, MESSAGE, FRIEND_REQUEST, FRIEND_BIRTHDAY, SEND_EMAIL_MESSAGE,
    FRIEND_APPROVE, FRIEND_BLOCKED, FRIEND_UNBLOCKED, FRIEND_SUBSCRIBE, USER_BIRTHDAY
}
